parameters:
#    pos_item.example.class: Pos\ItemBundle\Example

services:
#    pos_item.example:
#        class: %pos_item.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
