parameters:
#    pos_user.example.class: Pos\UserBundle\Example

services:
#    pos_user.example:
#        class: %pos_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
