pos_customer_manage:
    pattern:   /customer/manage/
    defaults: { _controller: PosCustomerBundle:Manage:index, page : 1 }
    requirements: 
        page: \d+

pos_customer_manage_list:
    pattern:   /customer/manage/page/{page}
    defaults: { _controller: PosCustomerBundle:Manage:index, page : 1 }
    requirements: 
        page: \d+
        
pos_customer_manage_edit:
    pattern:   /customer/manage/edit/{customer_id}
    defaults: { _controller: PosCustomerBundle:Manage:edit, page : 1 }
    requirements: 
        page: \d+

pos_customer_manage_view:
    pattern:   /customer/manage/view/
    defaults: { _controller: PosCustomerBundle:Manage:index, page : 1 }
    requirements: 
        page: \d+