pos_customer_manage:
    pattern:   /customer/manage/
    defaults: { _controller: PosCustomerBundle:Manage:index, page : 1 }
    requirements: 
        page: \d+

pos_customer_manage_list:
    pattern:   /customer/manage/page/{page}
    defaults: { _controller: PosCustomerBundle:Manage:index, page : 1 }
    requirements: 
        page: \d+
        
pos_customer_manage_edit:
    pattern:   /customer/manage/edit/{customer_id}
    defaults: { _controller: PosCustomerBundle:Manage:edit, customer : 1 }
    requirements: 
        customer: \d+

pos_customer_manage_add_child:
    pattern:   /customer/manage/addChild/{customer_id}
    defaults: { _controller: PosCustomerBundle:Manage:addChild, customer : 1 }
    requirements:
        customer: \d+

pos_customer_manage_add:
    pattern:   /customer/manage/add/
    defaults: { _controller: PosCustomerBundle:Manage:add}

pos_customer_manage_view:
    pattern:   /customer/manage/view/
    defaults: { _controller: PosCustomerBundle:Manage:index, page : 1 }
    requirements: 
        page: \d+