<?php

namespace Pos\SaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderDetailProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailProductRepository extends EntityRepository
{
}
