pos_sale:
    resource: "@PosSaleBundle/Resources/config/routing.yml"
    prefix:   /

pos_product:
    resource: "@PosProductBundle/Resources/config/routing.yml"
    prefix:   /

pos_paginator:
    resource: "@PosPaginatorBundle/Resources/config/routing.yml"
    prefix:   /

pos_customer:
    resource: "@PosCustomerBundle/Resources/config/routing.yml"
    prefix:   /

pos_home:
    resource: "@PosHomeBundle/Resources/config/routing.yml"
    prefix:   /

pos_user:
    resource: "@PosUserBundle/Resources/config/routing.yml"
    prefix:   /

pos_hr:
    resource: "@PosHRBundle/Resources/config/routing.yml"
    prefix:   /

