<?php

namespace Pos\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VatRepository extends EntityRepository
{
}
