<?php

namespace Pos\PointOfSalesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaleSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleSessionRepository extends EntityRepository
{
}
