pos_sale_homepage:
    pattern:  /sales
    defaults: { _controller: PosSaleBundle:Default:index }

pos_sale_sales_point:
    pattern:  /sales/point-of-sales
    defaults: { _controller: PosSaleBundle:OutletStore:index }