parameters:
#    pos_product.example.class: Pos\ProductBundle\Example

services:
#    pos_product.example:
#        class: %pos_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
